### PR TITLE
Add release-team-shadow-stats-report template

### LINKED ISSUE #8: Define release-team-shadow report
Currently, the diagrams (see [charts in the example folder](https://github.com/kubernetes-sigs/release-team-shadow-stats/tree/main/examples/plots)) are not structured. To share this information, a simple report template should be defined. This report should be publicly available and must be coordinated with ContribEx.

depending issue: [consult contribex which charts can be shared publicly in a report](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/7).

ref tracking issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

Add release-team-shadow-stats-report template. (see [report template](https://github.com/leonardpahlke/release-team-shadow-stats/blob/release-team-shadow-stats-report/examples/reports/report-template.md))

Fixes #8 

ref tracking issue: https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

/cc @jberkus

cc @cici37 @reylejano

### CODE REVIEW

**Comment by jberkus** [comment]
Questions:

1. What's the difference between "company affiliation" and "affiliation"?
2. The new shadow questionnaire has more detail on number of re-applications.  These charts don't seem to reflect that.  That data breaks down in to 4 categories, and would be interesting to see overall, for accepted shadows, and for not accepted shadows
  - first time applicants
  - second time applicants
  - third+ applicants
  - previously served on RT
3. Has the CoCC cleared having a pronouns chart?

**Comment by leonardpahlke** [comment]
> What's the difference between "company affiliation" and "affiliation"?

fixed

> The new shadow questionnaire has more detail on number of re-applications. These charts don't seem to reflect that. That data breaks down in to 4 categories, and would be interesting to see overall, for accepted shadows, and for not accepted shadows

yes! I need to update the code to reflect that .. until then we can keep this PR on hold.
I opened a issue for that see https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/11

(+) we can also create a new chart for _Which Release Team roles have you served in?_ (returners can select that)

Until we got the example charts I added a TBD to the report template, see https://github.com/leonardpahlke/release-team-shadow-stats/blob/release-team-shadow-stats-report/examples/reports/report-template.md#newcomer-re-applications

> previously served on RT

this is shown in the [_Returners, Newcomers_ chart](https://github.com/leonardpahlke/release-team-shadow-stats/blob/release-team-shadow-stats-report/examples/reports/report-template.md#returners-newcomers)

> Has the CoCC cleared having a pronouns chart?

not yet , I pinged CoCC again - lets see..>

@cpanato @palnabarun could you comment, thank you! :)

**Comment by leonardpahlke** [comment]
This PR adds a template which we use to publish RT shadow application reports to the community.

@jberkus you could take another look at type diagrams and check if they can be published (the specific ones added here are based on example/ sample data...)

cc 1.27 RT Lead & EA @salaxander & @JamesLaverack

**Comment by jberkus** [comment]
Those look fine to start with.

For companies, you're going to want to cut off any company that only has one applicant.

I'll probably want to re-plot the time zone chart to be more useful (think ordered bands), but I can do that later.

**Comment by JamesLaverack** [comment]
Looks good! For the actual 1.27 data I'll need to do some sanitation on the data anyway, for example for employer some applicants put "Student" and some put "student" along with other similar differences in spelling.

**Comment by leonardpahlke** [comment]
> For companies, you're going to want to cut off any company that only has one applicant.

Right, thats something we already have implemented by setting the **CLEAN_THRESHOLD** setting.

example:
```python
BasicChart("Test Company", ["Company"],
                   plotting_count_entities_up,
                   {CLEAN_KEYWORDS: company_keywords, CLEAN_THRESHOLD: 2})
```


> I'll probably want to re-plot the time zone chart to be more useful (think ordered bands)

Yes, right now we just have the pie-charts .. thats something we should improve for better data visualisation :+1:

**Comment by jberkus** [comment]
> Looks good! For the actual 1.27 data I'll need to do some sanitation on the data anyway, for example for employer some applicants put "Student" and some put "student" along with other similar differences in spelling.

I don't think there's any getting around data cleaning by hand.  I mean, for that matter some people are going to enter "Red Hat" and some "RedHat" and some "Red Hat Inc.", and we'll need to make those consistent.

**Comment by leonardpahlke** [comment]
> I don't think there's any getting around data cleaning by hand. I mean, for that matter some people are going to enter "Red Hat" and some "RedHat" and some "Red Hat Inc.", and we'll need to make those consistent.

There is some automatic data cleaning via "Keywords" and "Aliases". https://github.com/kubernetes-sigs/release-team-shadow-stats/blob/main/src/defaults.py#L46

```python
company_keywords = [
    "student",
    "liquid reply",
    "vmware",
    "microsoft",
    "red hat",
    "cisco",
    "ibm",
    "apple",
    "suse",
    "google",
    "independent",
    "deloitte",
    "adeste"
]

company_aliases = {
    "redhat": "red hat",
    "freelancer": "independent",
    "independant": "independent"
}
```

@JamesLaverack we could add to this or make this functionality somehow smarter

**Comment by leonardpahlke** [comment]
/unhold

@jberkus could you take another look & @xmudrii for approval - thanks :)

**Pull request closed without merging**
