### PR TITLE
Update README's - add new examples/README to help browsing the examples

### LINKED ISSUE #12: Highlight that the examples are being generated with fake / dummy data
Quite a few questions about the files in the `examples/` folder have been if these are files generated with real data or fake data. It should get highligted that these **files are based on fake data** and do not leak any information.

Highlight this in the following files:
- [x] Update README.md
- [x] Add a README.md under the examples folder 

cc @reylejano for suggesting this in [a discussion on a related issue](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/7#issuecomment-1098562404)

ref tracking issue https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/4

### PR DESCRIPTION
**Pull request by leonardpahlke**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

1. This PR adds a `/examples/README.md` which should help browsing the example data. 
2. Highlight that the examples are generated with fake data
3. Update `/README.md` (remove some older comments...)

#### Which issue(s) this PR fixes:

Fixes #12 

#### Special notes for your reviewer:

ref tracking issue: #4 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by leonardpahlke** [comment]
cc @reylejano

**Comment by leonardpahlke** [comment]
@saschagrunert & @puerco if you find time for a review :pray: I just made changes to README's with this PR

/assign @justaugustus

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
